version: 0.2
phases:
    pre_build:
        commands:
            - export DLLVERSION=$(date +1.0.%y%j.%H%M)
            - echo "<BUILDINFO>" >> buildinfo.xml
            - echo "<CODEBUILD_BUILD_ID>"$CODEBUILD_BUILD_ID"</CODEBUILD_BUILD_ID>" >> buildinfo.xml
            - echo "<CODEBUILD_SOURCE_VERSION>"$CODEBUILD_SOURCE_VERSION"</CODEBUILD_SOURCE_VERSION>" >> buildinfo.xml
            - echo "<DLLVERSION>"$DLLVERSION"</DLLVERSION>" >> buildinfo.xml
            - echo "<CODEBUILD_BUILD_IMAGE>"$CODEBUILD_BUILD_IMAGE"</CODEBUILD_BUILD_IMAGE>" >> buildinfo.xml
            - echo "<CODEBUILD_INITIATOR>"$CODEBUILD_INITIATOR"</CODEBUILD_INITIATOR>" >> buildinfo.xml
            - echo "<CODEUBUILD_KMS_KEY_ID>"$CODEUBUILD_KMS_KEY_ID"</CODEUBUILD_KMS_KEY_ID>" >> buildinfo.xml
            - echo "</BUILDINFO>" >> buildinfo.xml
            - sed -i 's#\\#/#g' SuperNova.DiscordBot.sln
            
    build:
        commands:
            - dotnet restore
            - dotnet build SuperNova.DiscordBot.sln -c Release /fl /p:Version=$DLLVERSION /p:DebugSymbols=false /p:DebugType=None
    post_build:
        commands:
artifacts:
    files:
        - "buildInfo.xml"
        - "bin/*.dll"
        - "bin/*.json"
        - "serverless.yml"
    discard-paths: yes